# Generated by Django 5.1.2 on 2024-10-21 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracticeapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="artist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shows",
                to="tracticeapi.artist",
            ),
        ),
    ]
