# Generated by Django 5.1.2 on 2024-10-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracticeapi", "0002_show_artist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="artist",
        ),
    ]
